### ISSUE TITLE
dyld: Symbol not found:

### ISSUE THREAD

**Issue by Rnorback** [johnno1962/InjectionApp#30]
Hey John,

Keep running into this error.  Not sure how to fix it.  Tried cleaning the project, learning derived data, and restarting Xcode.  I'm on Xcode 9 beta 3.  Any thoughts on a direction forward?

2017-07-24 22:28:07.886387-0700 Chime_Staging[91643:6932742] Injection attempting connection to: 127.0.0.1:31452
2017-07-24 22:28:07.887097-0700 Chime_Staging[91643:6932742] Connected to "Injection" plugin, ready to load x86_64 code.
Compiling /Users/robnorback/Desktop/Chime/client-ios-swift/Chime/View Controllers/Support/CreateTicketViewController.swift
objc[91643]: Class _TtC13Chime_Staging26CreateTicketViewController is implemented in both /Users/robnorback/Library/Developer/CoreSimulator/Devices/20609306-D9AE-4642-BE95-ED3E5486A9E8/data/Containers/Bundle/Application/2BEC07EB-857B-4359-9A03-5CC9D085FC4C/Chime_Staging.app/Chime_Staging (0x109e66358) and /Users/robnorback/Library/Developer/Xcode/DerivedData/Chime-cdlssfexgwhtehahbluwvzobtrug/Logs/iOSInjectionProject/build/Debug-iphonesimulator/InjectionBundle5.bundle/InjectionBundle (0x13d0be1b8). One of the two will be used. Which one is undefined.
2 injections performed so far.
2017-07-24 22:28:09.144650-0700 Chime_Staging[91643:6924515] Ignore any warning, Swizzled Chime_Staging.CreateTicketViewController 0x13d0be1b8 -> 0x109e66358
dyld: lazy symbol binding failed: Symbol not found: __T0S2SSgSPys4Int8VG14validatingUTF8_tcfCTfq4nd_n
  Referenced from: /Applications/Injection.app/Contents/Resources/InjectionLoader.bundle/XprobeSwift.loader/XprobeSwift
  Expected in: /Users/robnorback/Library/Developer/CoreSimulator/Devices/20609306-D9AE-4642-BE95-ED3E5486A9E8/data/Containers/Bundle/Application/2BEC07EB-857B-4359-9A03-5CC9D085FC4C/Chime_Staging.app/Frameworks/libswiftCore.dylib

dyld: Symbol not found: __T0S2SSgSPys4Int8VG14validatingUTF8_tcfCTfq4nd_n
  Referenced from: /Applications/Injection.app/Contents/Resources/InjectionLoader.bundle/XprobeSwift.loader/XprobeSwift
  Expected in: /Users/robnorback/Library/Developer/CoreSimulator/Devices/20609306-D9AE-4642-BE95-ED3E5486A9E8/data/Containers/Bundle/Application/2BEC07EB-857B-4359-9A03-5CC9D085FC4C/Chime_Staging.app/Frameworks/libswiftCore.dylib

**Comment by johnno1962** [comment]
Can you try the new Xcode 9 version: http://johnholdsworth.com/Injection9.app.zip ? It should fix this.

**Comment by Rnorback** [comment]
Will do, thought I was, but maybe didn't have the latest and greatest.

**Comment by johnno1962** [comment]
There was an update last night

**Comment by Rnorback** [comment]
Still getting this

1 injections performed so far.
Injection: Ignore any warning, Swizzled Chime_Staging.CreateTicketViewController 0x1363e51b8 -> 0x1038bd358
dyld: lazy symbol binding failed: Symbol not found: __T0SS10FoundationE20replacingOccurrencesS2S2of_SS4withSo8NSStringC14CompareOptionsV7optionss5RangeVySS5IndexVGSg5rangetFfA1_
  Referenced from: /Applications/Injection.app/Contents/Resources/InjectionLoader.bundle/XprobeSwift.loader/XprobeSwift
  Expected in: /Users/robnorback/Library/Developer/CoreSimulator/Devices/20609306-D9AE-4642-BE95-ED3E5486A9E8/data/Containers/Bundle/Application/3484F897-BB5E-4BAC-A5F5-9A1FDD1B2E5A/Chime_Staging.app/Frameworks/libswiftFoundation.dylib

dyld: Symbol not found: __T0SS10FoundationE20replacingOccurrencesS2S2of_SS4withSo8NSStringC14CompareOptionsV7optionss5RangeVySS5IndexVGSg5rangetFfA1_
  Referenced from: /Applications/Injection.app/Contents/Resources/InjectionLoader.bundle/XprobeSwift.loader/XprobeSwift
  Expected in: /Users/robnorback/Library/Developer/CoreSimulator/Devices/20609306-D9AE-4642-BE95-ED3E5486A9E8/data/Containers/Bundle/Application/3484F897-BB5E-4BAC-A5F5-9A1FDD1B2E5A/Chime_Staging.app/Frameworks/libswiftFoundation.dylib

from this code 

```
@objc func injected() {
        self.view.subviews.flatMap {
            $0.removeFromSuperview()
        }
        
     viewDidLoad()
}
```

**Comment by johnno1962** [comment]
That’s dissapointing. The new version is built with beta4. Have you tried that? Swift 4 is sitll bedding in.

**Comment by Rnorback** [comment]
I'll try beta 4, let me know if I can give you any other info to help with this.

**Comment by Rnorback** [comment]
Got it to work! Upgraded to the latest version of injection and Xcode 9 beta 4.  Thanks so much John.
